defaults:
  - model: modular_leadmm5
  - metrics: reconstruction_full
  - datasets: digicam_eval
  - dataloader: digicam
  - transforms: none_transforms
  - _self_

inferencer:
  device_tensors: ["lensless", "psf", "lensed_roi"]
  device: auto
  save_path: reconstructions
  seed: 1
  from_pretrained: checkpoints/leadmm5-pre_post/model_best.pth
  skip_model_load: false